// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "a4TjEvvtxOrzg6WpzHH4d7UaTFhHqSVs4eqAvn9kUP4CRslTsNJpHpW6zPcnt1XAJaHgWw";
}
}
}

